name: Install newer bash (5.3)

runs:
  using: composite
  steps:
    - name: Install bash 5.3 (macOS)
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: brew install bash

    - name: Install bash 5.3 (Linux)
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        set -e
        wget https://archive.ubuntu.com/ubuntu/pool/universe/b/bash/bash-static_5.3-1ubuntu1_amd64.deb
        dpkg --fsys-tarfile bash-static_5.3-1ubuntu1_amd64.deb | tar -xO ./usr/bin/bash-static > /usr/local/bin/bash
        chmod +x /usr/local/bin/bash
